FROM python:3.10

COPY . /app
WORKDIR /app

RUN apt-get update
RUN apt-get -y install libgl1-mesa-glx
RUN pip install --no-cache-dir -r requirements.txt

ENV RESOURCE=pp3-resource-dev
ENV RESOURCE_PORT=8080
ENV PORT=9888
CMD uvicorn app:app --host 0.0.0.0 --port ${PORT}